name: Push OSPF Config to Device

on:
  push:
    paths:
      - 'configs/*.cfg'

jobs:
  push_config:
    runs-on: ubuntu-latest

    env:
      MCP_URL: http://198.11.21.101:8000

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Determine Device and Config
      id: vars
      run: |
        FILE_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^configs/' | head -n 1)
        DEVICE=$(basename "$FILE_CHANGED" | cut -d_ -f1)
        echo "device=$DEVICE" >> $GITHUB_OUTPUT
        echo "file_path=$FILE_CHANGED" >> $GITHUB_OUTPUT

    - name: Ping Device
      run: |
        DEVICE=${{ steps.vars.outputs.device }}
        IP=$(curl -s "$MCP_URL/inventory/interface_ips?rtr=$DEVICE" | jq -r '.[].Management0 // .[].Ethernet1 // .[]')
        echo "Resolved IP: $IP"
        ping -c 3 "$IP"

    - name: Push config to device
      run: |
        curl -X POST "$MCP_URL/push/config" \
          -H "Content-Type: application/json" \
          -d '{"device": "${{ steps.vars.outputs.device }}", "config_file": "${{ steps.vars.outputs.file_path }}"}'

