name: Push All Configs Found in /configs

on:
  push:
    paths:
      - 'configs/*.cfg'

jobs:
  push_configs:
    runs-on: ubuntu-latest

    env:
      MCP_URL: http://198.11.21.101:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Loop and push all .cfg files
        run: |
          for file in configs/*.cfg; do
            DEVICE=$(basename "$file" | cut -d_ -f1)
            echo "📡 Pushing config for $DEVICE ($file)"
            curl -X POST "$MCP_URL/push/config" \
              -H "Content-Type: application/json" \
              -d "{\"device\": \"$DEVICE\", \"config_file\": \"$file\"}"
          done

